const API="https://rescueroute-api.onrender.com";let incidents=[],vehicles=[],dashMap,fullMap,selected=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
document.addEventListener("DOMContentLoaded",()=>{bind();if(localStorage.getItem("rr_logged")==="1")showApp()});
function bind(){
 $("#loginForm").onsubmit=e=>{e.preventDefault();localStorage.setItem("rr_logged","1");showApp()};
 $("#togglePass").onclick=()=>{const x=$("#loginPassword");x.type=x.type==="password"?"text":"password";$("#togglePass").textContent=x.type==="password"?"Show":"Hide"};
 $("#logout").onclick=()=>{localStorage.removeItem("rr_logged");location.reload()};
 $$(".nav").forEach(n=>n.onclick=()=>page(n.dataset.page));$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
 $$("[data-go]").forEach(x=>x.onclick=()=>page(x.dataset.go));
 $("#newBtn").onclick=$("#newBtn2").onclick=()=>open("incidentModal");
 $$("[data-close]").forEach(x=>x.onclick=()=>close(x.dataset.close));
 $("#incidentForm").onsubmit=createIncident;$("#confirm").onclick=dispatch;$("#search").oninput=renderTable;$("#sev").onchange=renderTable;$("#stat").onchange=renderTable;
}
async function showApp(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");await load()}
function page(p){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+p).classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#title").textContent=p==="map"?"Live Map":p[0].toUpperCase()+p.slice(1);$("#sidebar").classList.remove("open");setTimeout(()=>{if(dashMap)dashMap.invalidateSize();if(fullMap)fullMap.invalidateSize()},100)}
async function api(path,opt={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...opt});if(!r.ok){let m="Request failed";try{m=(await r.json()).message||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
async function load(){try{const [d,i,v]=await Promise.all([api("/dashboard/summary"),api("/incidents"),api("/vehicles")]);incidents=i||[];vehicles=v||[];kpis(d);render();maps();draw()}catch(e){toast("Backend not connected — start Spring Boot first.");console.error(e)}}
function kpis(d){$$("[data-k]").forEach(e=>{const n=Number(d[e.dataset.k]||0),s=performance.now();function f(t){let p=Math.min(1,(t-s)/600);e.textContent=Math.round(n*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)})}
const rank=s=>({CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3}[s]??4),sc=s=>(s||"LOW").toLowerCase();
function render(){const sorted=[...incidents].filter(x=>x.status!=="COMPLETED").sort((a,b)=>rank(a.severity)-rank(b.severity)||new Date(a.createdAt||0)-new Date(b.createdAt||0));$("#queue").innerHTML=sorted.slice(0,7).map((x,i)=>`<div class="qrow"><i class="dot ${sc(x.severity)}"></i><div><b>#${x.id} · ${x.type}</b><small>${x.status} · ${x.description||"Emergency reported"}</small></div><span class="push">${String(i+1).padStart(2,"0")}</span></div>`).join("")||empty("No pending emergencies");
$("#active").innerHTML=incidents.filter(x=>x.status!=="COMPLETED"&&x.status!=="CANCELLED").slice(0,6).map(x=>`<div class="row"><i class="dot ${sc(x.severity)}"></i><div><b>#${x.id} · ${x.type}</b><small>${x.description||"Emergency"}</small></div><span class="badge ${sc(x.severity)}">${x.severity}</span>${x.status==="PENDING"?`<button class="text" onclick="openDispatch(${x.id})">Dispatch</button>`:""}</div>`).join("")||empty("No active incidents");
$("#fleet").innerHTML=vehicles.slice(0,6).map(v=>`<div class="row"><div class="vicon" style="width:34px;height:34px;font-size:14px">▣</div><div><b>${v.vehicleNumber||v.vehicle_number}</b><small>${v.type}</small></div><span class="status ${v.status==="AVAILABLE"?"":v.status==="OFFLINE"?"offline":"busy"}">${v.status}</span></div>`).join("")||empty("No vehicles");
renderTable();$("#vehicleGrid").innerHTML=vehicles.map(v=>`<article class="vehicle"><div class="vtop"><div class="vicon">▣</div><span class="status ${v.status==="AVAILABLE"?"":v.status==="OFFLINE"?"offline":"busy"}">${v.status}</span></div><h3>${v.vehicleNumber||v.vehicle_number}</h3><p>${v.type}</p><div class="vmeta"><div class="meta"><span>Workload</span><b>${v.workload||0} assignments</b></div><div class="meta"><span>Location</span><b>${Number(v.latitude).toFixed(3)}, ${Number(v.longitude).toFixed(3)}</b></div></div></article>`).join("")}
function renderTable(){const q=($("#search")?.value||"").toLowerCase(),s=$("#sev")?.value||"",st=$("#stat")?.value||"";const a=incidents.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!s||x.severity===s)&&(!st||x.status===st));$("#table").innerHTML=a.map(x=>`<tr><td>#${x.id}</td><td>${x.type}</td><td><span class="badge ${sc(x.severity)}">${x.severity}</span></td><td><span class="status">${x.status}</span></td><td>${Number(x.latitude).toFixed(3)}, ${Number(x.longitude).toFixed(3)}</td><td>${date(x.createdAt)}</td><td>${x.status==="PENDING"?`<button class="primary" style="padding:7px 9px" onclick="openDispatch(${x.id})">Dispatch</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="7" style="text-align:center;padding:30px">No matching incidents.</td></tr>`}
function date(x){if(!x)return"—";return new Date(x).toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function empty(x){return`<div style="padding:25px;text-align:center;color:#9aa6b5;font-size:10px">${x}</div>`}
function open(id){$("#"+id).classList.add("show")}function close(id){$("#"+id).classList.remove("show")}
async function createIncident(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.latitude=+d.latitude;d.longitude=+d.longitude;try{await api("/incidents",{method:"POST",body:JSON.stringify(d)});close("incidentModal");toast("Emergency created.");e.target.reset();await load()}catch(e){toast(e.message)}}
function openDispatch(id){selected=incidents.find(x=>+x.id===+id);if(!selected)return;const avail=vehicles.filter(v=>v.status==="AVAILABLE").length;$("#dispatchInfo").innerHTML=`<div class="dline"><span>Incident</span><b>#${selected.id} · ${selected.type}</b></div><div class="dline"><span>Severity</span><b>${selected.severity}</b></div><div class="dline"><span>Location</span><b>${Number(selected.latitude).toFixed(4)}, ${Number(selected.longitude).toFixed(4)}</b></div><div class="dline"><span>Available units</span><b>${avail}</b></div><div class="dline"><span>Selection rule</span><b>Nearest eligible vehicle</b></div>`;open("dispatchModal")}
async function dispatch(){if(!selected)return;$("#confirm").disabled=true;$("#confirm").textContent="Dispatching…";try{const r=await api("/dispatch",{method:"POST",body:JSON.stringify({incidentId:selected.id})});close("dispatchModal");toast(`Dispatch created · ${r.vehicleNumber||"unit"} assigned`);await load()}catch(e){toast(e.message)}finally{$("#confirm").disabled=false;$("#confirm").textContent="Confirm Dispatch"}}
function maps(){if(dashMap||typeof L==="undefined")return;const c=[12.9716,77.5946],tiles="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";dashMap=L.map("dashMap").setView(c,12);fullMap=L.map("fullMap").setView(c,12);L.tileLayer(tiles,{attribution:"© OpenStreetMap contributors"}).addTo(dashMap);L.tileLayer(tiles,{attribution:"© OpenStreetMap contributors"}).addTo(fullMap);draw()}
function draw(){if(!dashMap)return;[dashMap,fullMap].forEach(m=>m.eachLayer(x=>{if(x instanceof L.Marker)m.removeLayer(x)}));incidents.forEach(x=>{if(x.latitude==null)return;const col=x.severity==="CRITICAL"?"#e64e58":x.severity==="HIGH"?"#ef9b35":"#367fc5";const ic=L.divIcon({className:"",html:`<div style="width:17px;height:17px;border-radius:50%;background:${col};border:3px solid white;box-shadow:0 3px 10px #0003"></div>`,iconSize:[17,17]});[dashMap,fullMap].forEach(m=>L.marker([x.latitude,x.longitude],{icon:ic}).addTo(m).bindPopup(`<b>#${x.id} ${x.type}</b><br>${x.severity} · ${x.status}`))});vehicles.forEach(v=>{if(v.latitude==null)return;const ic=L.divIcon({className:"",html:`<div style="width:25px;height:25px;border-radius:8px;background:#1768c4;color:white;border:3px solid white;display:grid;place-items:center;box-shadow:0 3px 10px #0003">▣</div>`,iconSize:[25,25]});[dashMap,fullMap].forEach(m=>L.marker([v.latitude,v.longitude],{icon:ic}).addTo(m).bindPopup(`<b>${v.vehicleNumber||v.vehicle_number}</b><br>${v.type} · ${v.status}`))})}
let timer;function toast(x){$("#toast").textContent=x;$("#toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("#toast").classList.remove("show"),2800)}
